name: Mod addition request
description: Add a mod to the modpack
labels: ["enhancement", "needs review"]
assignees:
  - TheModdersDen
body:
  - type: markdown
    attributes:
      value: |
        Before opening a mod addition request, please search for any existing, similar, matches before filing a new one. If you find an existing one, please add a 👍 reaction to it. 
        Please do not reply 'bump' or use similar means to make the mod addition request more visible. This will not help your case and will only annoy the maintainers, which may result in your request being denied or removed.
        
        ---
        
        Thank you for taking the time to file a mod addition request. Please provide as much information as possible so we can review your request as fast as possible.
  - type: input
    id: os
    attributes:
      label: Operating System
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "macOS Big Sur 11.5.2"
    validations:
      required: true  
  - type: input
    id: java_version
    attributes:
      label: Java Version
      description: "Please provide the full Java version installed on your computer. You can find this by running `java -version` in your terminal"
      placeholder: "openjdk version \"11.0.12\" 2021-07-20"
    validations:
      required: true
  - type: input
    id: mc_version
    attributes:
      label: Minecraft Version
      description: "Please provide the full Minecraft version that you are running currently, in addition to the type."
      placeholder: "1.17.1 Forge"
    validations:
      required: true
  - type: input
    id: modpack_version
    attributes:
      label: Modpack Version
      description: "Please provide the full modpack version that you are running currently. Please do not use the word `latest` here, as this will change over time."
      placeholder: "2.3.0"
    validations:
      required: true
  - type: textarea
    id: mod-name
    attributes:
      label: Mod Name
      description: What is the name of the mod you want to add?
    validations:
      required: true
  - type: textarea
    id: mod_version
    attributes:
      label: Mod Version
      description: What is the version of the mod you want to add?
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: Shell
  - type: input
    id: mod_reason
    attributes:
      label: Mod Addition Reason
      description: Why do you want to add this mod? Why should we add this mod? Why will it be useful for the modpack? Etc...
      placeholder: "I want to add this mod because..."
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/TheModdersDen/ModpackTemplate/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true